services:
  - type: web
    name: goat-farm-backend
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: FIRST_ADMIN_NAME
        value: Admin
      - key: FIRST_ADMIN_EMAIL
        value: admin@goatfarm.com
      - key: FIRST_ADMIN_PASSWORD
        value: Admin@123
      - key: CORS_ORIGINS
        value: "*"
